// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// trainFM
List trainFM(List j14924k);
RcppExport SEXP FactoRizationMachines_trainFM(SEXP j14924kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type j14924k(j14924kSEXP);
    rcpp_result_gen = Rcpp::wrap(trainFM(j14924k));
    return rcpp_result_gen;
END_RCPP
}
// predictFM
NumericVector predictFM(List j14924k);
RcppExport SEXP FactoRizationMachines_predictFM(SEXP j14924kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type j14924k(j14924kSEXP);
    rcpp_result_gen = Rcpp::wrap(predictFM(j14924k));
    return rcpp_result_gen;
END_RCPP
}
