# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trainFM <- function(j11161k) {
    .Call(`_FactoRizationMachines_trainFM`, j11161k)
}

predictFM <- function(j11161k) {
    .Call(`_FactoRizationMachines_predictFM`, j11161k)
}

