# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trainFM <- function(j14924k) {
    .Call('FactoRizationMachines_trainFM', PACKAGE = 'FactoRizationMachines', j14924k)
}

predictFM <- function(j14924k) {
    .Call('FactoRizationMachines_predictFM', PACKAGE = 'FactoRizationMachines', j14924k)
}

